--- 
docker_build:
  before_script:
    - "echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY"
  image: "docker:latest"
  only:
    - tags
  script:
    - "cd subsystems/cont_proc"
    - "docker build --no-cache --force-rm -t $CI_REGISTRY_IMAGE/pq:$CI_COMMIT_TAG ."
    - "docker push $CI_REGISTRY_IMAGE/pq:$CI_COMMIT_TAG"
  services:
    - "docker:dind"
  stage: Build
sonarqube: 
  allow_failure: true
  image: 
    entrypoint: 
      - ""
    name: "sonarsource/sonar-scanner-cli:latest"
  script: 
    - "echo \"Running sonarqube...\""
    - "cd subsystems/"
    - "sonar-scanner -Dsonar.qualitygate.wait=true -Dsonar.projectKey=i4Q_PQ -Dsonar.sources=. -Dsonar.host.url=${SONAR_HOST_URL} -Dsonar.login=${SONAR_TOKEN} -Dsonar.java.binaries=."
  stage: Quality
stages: 
  - Quality
  - Build
